version: "3.3"

# Docker Services
services:

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: deploy/local/dockerfiles/Postgres.Dockerfile
    environment:
      POSTGRES_DB: pgrailsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2020!"
      POSTGRES_HOST: 0.0.0.0
    volumes:
      - postgresdbdata:/var/lib/postgresql/data
    networks:
      - rails_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 3

  railspg_local:
    container_name: rails_local
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    networks:
      - rails_network
    build:
      context: .
      dockerfile: deploy/local/dockerfiles/Rails.Dockerfile
    volumes:
      - ./app:/app
      - bundlecachedata:/usr/local/bundle
    env_file:
      - deploy/local/.env

  rails_local:
    container_name: rails_local
    tty: true
    stdin_open: true
    networks:
      - rails_network
    build:
      context: .
      dockerfile: deploy/local/dockerfiles/Rails.Dockerfile
    volumes:
      - ./app:/app
      - bundlecachedata:/usr/local/bundle
    env_file:
      - deploy/local/.env


# Docker Networks
networks:
  rails_network:
    driver: bridge

# Docker Volumes
volumes:
  postgresdbdata:
  bundlecachedata:
